[2025-06-18T13:28:00.112+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-18T13:28:00.141+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: usdpkr_forecasting_modular.train_lasso manual__2025-06-18T13:24:27.904551+00:00 [queued]>
[2025-06-18T13:28:00.149+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: usdpkr_forecasting_modular.train_lasso manual__2025-06-18T13:24:27.904551+00:00 [queued]>
[2025-06-18T13:28:00.150+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 3
[2025-06-18T13:28:00.163+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): train_lasso> on 2025-06-18 13:24:27.904551+00:00
[2025-06-18T13:28:00.168+0000] {standard_task_runner.py:63} INFO - Started process 7990 to run task
[2025-06-18T13:28:00.171+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'usdpkr_forecasting_modular', 'train_lasso', 'manual__2025-06-18T13:24:27.904551+00:00', '--job-id', '748', '--raw', '--subdir', 'DAGS_FOLDER/usdpkr_forecasting_dag.py', '--cfg-path', '/tmp/tmpu02099hy']
[2025-06-18T13:28:00.173+0000] {standard_task_runner.py:91} INFO - Job 748: Subtask train_lasso
[2025-06-18T13:28:00.211+0000] {task_command.py:426} INFO - Running <TaskInstance: usdpkr_forecasting_modular.train_lasso manual__2025-06-18T13:24:27.904551+00:00 [running]> on host 9c4806d77c92
[2025-06-18T13:28:00.294+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='usdpkr_forecasting_modular' AIRFLOW_CTX_TASK_ID='train_lasso' AIRFLOW_CTX_EXECUTION_DATE='2025-06-18T13:24:27.904551+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-18T13:24:27.904551+00:00'
[2025-06-18T13:28:00.295+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-18T13:28:00.306+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-18T13:28:00.306+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: train_lasso_model() missing 2 required positional arguments: 'selected_features_path' and 'train_test_data_path'
[2025-06-18T13:28:00.313+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=usdpkr_forecasting_modular, task_id=train_lasso, run_id=manual__2025-06-18T13:24:27.904551+00:00, execution_date=20250618T132427, start_date=20250618T132800, end_date=20250618T132800
[2025-06-18T13:28:00.322+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 748 for task train_lasso (train_lasso_model() missing 2 required positional arguments: 'selected_features_path' and 'train_test_data_path'; 7990)
[2025-06-18T13:28:00.344+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-18T13:28:00.366+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-18T13:28:00.369+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
