[2025-06-18T17:00:03.872+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-18T17:00:03.903+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kse100_forecasting.fetch_kse100 manual__2025-06-18T16:55:19.331260+00:00 [queued]>
[2025-06-18T17:00:03.912+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kse100_forecasting.fetch_kse100 manual__2025-06-18T16:55:19.331260+00:00 [queued]>
[2025-06-18T17:00:03.913+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 6
[2025-06-18T17:00:03.929+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_kse100> on 2025-06-18 16:55:19.331260+00:00
[2025-06-18T17:00:03.935+0000] {standard_task_runner.py:63} INFO - Started process 3574 to run task
[2025-06-18T17:00:03.938+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'kse100_forecasting', 'fetch_kse100', 'manual__2025-06-18T16:55:19.331260+00:00', '--job-id', '1000', '--raw', '--subdir', 'DAGS_FOLDER/kse100_forecasting_dag.py', '--cfg-path', '/tmp/tmpzx8cisdr']
[2025-06-18T17:00:03.940+0000] {standard_task_runner.py:91} INFO - Job 1000: Subtask fetch_kse100
[2025-06-18T17:00:03.984+0000] {task_command.py:426} INFO - Running <TaskInstance: kse100_forecasting.fetch_kse100 manual__2025-06-18T16:55:19.331260+00:00 [running]> on host 57c57e92cb28
[2025-06-18T17:00:04.068+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kse100_forecasting' AIRFLOW_CTX_TASK_ID='fetch_kse100' AIRFLOW_CTX_EXECUTION_DATE='2025-06-18T16:55:19.331260+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-18T16:55:19.331260+00:00'
[2025-06-18T17:00:04.070+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-18T17:00:04.082+0000] {ingest.py:65} INFO - Fetching ^KSE from Yahoo Finance...
[2025-06-18T17:00:15.093+0000] {multi.py:184} ERROR - 
1 Failed download:
[2025-06-18T17:00:15.094+0000] {multi.py:197} ERROR - ['^KSE']: Timeout('Failed to perform, curl: (28) Operation timed out after 10001 milliseconds with 94363 bytes received. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')
[2025-06-18T17:00:15.103+0000] {ingest.py:112} ERROR - Error fetching ^KSE: No data downloaded for ticker '^KSE'
[2025-06-18T17:00:15.106+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-18T17:00:15.107+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/kse_modules/ingest.py", line 83, in fetch_yahoo_finance
    raise ValueError(f"No data downloaded for ticker '{ticker}'")
ValueError: No data downloaded for ticker '^KSE'
[2025-06-18T17:00:15.122+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=kse100_forecasting, task_id=fetch_kse100, run_id=manual__2025-06-18T16:55:19.331260+00:00, execution_date=20250618T165519, start_date=20250618T170003, end_date=20250618T170015
[2025-06-18T17:00:15.144+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 1000 for task fetch_kse100 (No data downloaded for ticker '^KSE'; 3574)
[2025-06-18T17:00:15.175+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-18T17:00:15.198+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-18T17:00:15.200+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
