[2025-06-14T15:30:19.629+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-14T15:30:19.698+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: usdpkr_forecasting_modular.fetch_gold scheduled__2025-05-01T00:00:00+00:00 [queued]>
[2025-06-14T15:30:19.708+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: usdpkr_forecasting_modular.fetch_gold scheduled__2025-05-01T00:00:00+00:00 [queued]>
[2025-06-14T15:30:19.719+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-06-14T15:30:19.758+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_gold> on 2025-05-01 00:00:00+00:00
[2025-06-14T15:30:19.766+0000] {standard_task_runner.py:63} INFO - Started process 358 to run task
[2025-06-14T15:30:19.783+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'usdpkr_forecasting_modular', 'fetch_gold', 'scheduled__2025-05-01T00:00:00+00:00', '--job-id', '177', '--raw', '--subdir', 'DAGS_FOLDER/usdpkr_forecasting_dag.py', '--cfg-path', '/tmp/tmpj1kws8k1']
[2025-06-14T15:30:19.791+0000] {standard_task_runner.py:91} INFO - Job 177: Subtask fetch_gold
[2025-06-14T15:30:19.966+0000] {task_command.py:426} INFO - Running <TaskInstance: usdpkr_forecasting_modular.fetch_gold scheduled__2025-05-01T00:00:00+00:00 [running]> on host 1ada37a5d2dc
[2025-06-14T15:30:20.214+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='usdpkr_forecasting_modular' AIRFLOW_CTX_TASK_ID='fetch_gold' AIRFLOW_CTX_EXECUTION_DATE='2025-05-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-01T00:00:00+00:00'
[2025-06-14T15:30:20.222+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-14T15:30:20.297+0000] {logging_mixin.py:188} INFO - Fetching GC=F from Yahoo Finance...
[2025-06-14T15:30:26.584+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-14T15:30:26.585+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "offsets.pyx", line 4447, in pandas._libs.tslibs.offsets._get_offset
KeyError: 'ME'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "offsets.pyx", line 4549, in pandas._libs.tslibs.offsets.to_offset
  File "offsets.pyx", line 4453, in pandas._libs.tslibs.offsets._get_offset
ValueError: Invalid frequency: ME

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/inflation_modules/ingest.py", line 37, in fetch_yahoo_finance
    df = df[[price_col]].resample('ME').last()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 9439, in resample
    return get_resampler(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/resample.py", line 1969, in get_resampler
    tg = TimeGrouper(**kwds)
         ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/resample.py", line 2046, in __init__
    freq = to_offset(freq)
           ^^^^^^^^^^^^^^^
  File "offsets.pyx", line 4460, in pandas._libs.tslibs.offsets.to_offset
  File "offsets.pyx", line 4557, in pandas._libs.tslibs.offsets.to_offset
ValueError: Invalid frequency: ME
[2025-06-14T15:30:26.600+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=usdpkr_forecasting_modular, task_id=fetch_gold, run_id=scheduled__2025-05-01T00:00:00+00:00, execution_date=20250501T000000, start_date=20250614T153019, end_date=20250614T153026
[2025-06-14T15:30:26.621+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 177 for task fetch_gold (Invalid frequency: ME; 358)
[2025-06-14T15:30:26.636+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-14T15:30:26.658+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-14T15:30:26.660+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
