[2025-06-18T17:15:27.187+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-18T17:15:27.277+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: usdpkr_forecasting.fetch_inflation manual__2025-06-18T17:15:18.237055+00:00 [queued]>
[2025-06-18T17:15:27.318+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: usdpkr_forecasting.fetch_inflation manual__2025-06-18T17:15:18.237055+00:00 [queued]>
[2025-06-18T17:15:27.325+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2025-06-18T17:15:27.392+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_inflation> on 2025-06-18 17:15:18.237055+00:00
[2025-06-18T17:15:27.451+0000] {standard_task_runner.py:63} INFO - Started process 4351 to run task
[2025-06-18T17:15:27.438+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'usdpkr_forecasting', 'fetch_inflation', 'manual__2025-06-18T17:15:18.237055+00:00', '--job-id', '1014', '--raw', '--subdir', 'DAGS_FOLDER/usdpkr_forecasting_dag.py', '--cfg-path', '/tmp/tmpuwecuu60']
[2025-06-18T17:15:27.472+0000] {standard_task_runner.py:91} INFO - Job 1014: Subtask fetch_inflation
[2025-06-18T17:15:27.646+0000] {task_command.py:426} INFO - Running <TaskInstance: usdpkr_forecasting.fetch_inflation manual__2025-06-18T17:15:18.237055+00:00 [running]> on host 57c57e92cb28
[2025-06-18T17:15:27.810+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='usdpkr_forecasting' AIRFLOW_CTX_TASK_ID='fetch_inflation' AIRFLOW_CTX_EXECUTION_DATE='2025-06-18T17:15:18.237055+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-18T17:15:18.237055+00:00'
[2025-06-18T17:15:27.813+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-18T17:15:27.829+0000] {ingest.py:130} INFO - Fetching 'INFLATION_YOY' from IMF (ID: PCPI_IX)...
[2025-06-18T17:15:33.889+0000] {ingest.py:177} ERROR - Error fetching IMF data for INFLATION_YOY: Expecting value: line 1 column 1 (char 0)
[2025-06-18T17:15:33.890+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-18T17:15:33.890+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/inflation_modules/ingest.py", line 136, in fetch_imf_data
    data = response.json()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2025-06-18T17:15:33.918+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=usdpkr_forecasting, task_id=fetch_inflation, run_id=manual__2025-06-18T17:15:18.237055+00:00, execution_date=20250618T171518, start_date=20250618T171527, end_date=20250618T171533
[2025-06-18T17:15:33.937+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 1014 for task fetch_inflation (Expecting value: line 1 column 1 (char 0); 4351)
[2025-06-18T17:15:33.958+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-18T17:15:33.980+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-18T17:15:33.982+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
