[2025-06-18T12:48:08.861+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-18T12:48:08.887+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: usdpkr_forecasting_modular.evaluate_lasso manual__2025-06-18T12:45:36.635411+00:00 [queued]>
[2025-06-18T12:48:08.895+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: usdpkr_forecasting_modular.evaluate_lasso manual__2025-06-18T12:45:36.635411+00:00 [queued]>
[2025-06-18T12:48:08.895+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 3
[2025-06-18T12:48:08.909+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): evaluate_lasso> on 2025-06-18 12:45:36.635411+00:00
[2025-06-18T12:48:08.915+0000] {standard_task_runner.py:63} INFO - Started process 6170 to run task
[2025-06-18T12:48:08.917+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'usdpkr_forecasting_modular', 'evaluate_lasso', 'manual__2025-06-18T12:45:36.635411+00:00', '--job-id', '691', '--raw', '--subdir', 'DAGS_FOLDER/usdpkr_forecasting_dag.py', '--cfg-path', '/tmp/tmpmdezq_db']
[2025-06-18T12:48:08.919+0000] {standard_task_runner.py:91} INFO - Job 691: Subtask evaluate_lasso
[2025-06-18T12:48:08.958+0000] {task_command.py:426} INFO - Running <TaskInstance: usdpkr_forecasting_modular.evaluate_lasso manual__2025-06-18T12:45:36.635411+00:00 [running]> on host 9c4806d77c92
[2025-06-18T12:48:09.048+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='usdpkr_forecasting_modular' AIRFLOW_CTX_TASK_ID='evaluate_lasso' AIRFLOW_CTX_EXECUTION_DATE='2025-06-18T12:45:36.635411+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-18T12:45:36.635411+00:00'
[2025-06-18T12:48:09.050+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-18T12:48:09.061+0000] {logging_mixin.py:188} INFO - Error in evaluate_lasso: selected_features_path must be a .pkl file, got: /opt/***/data/models/selected_features.csv
[2025-06-18T12:48:09.061+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-18T12:48:09.062+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/inflation_modules/model_steps.py", line 927, in evaluate_lasso
    raise ValueError(f"selected_features_path must be a .pkl file, got: {selected_features_path}")
ValueError: selected_features_path must be a .pkl file, got: /opt/***/data/models/selected_features.csv
[2025-06-18T12:48:09.074+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=usdpkr_forecasting_modular, task_id=evaluate_lasso, run_id=manual__2025-06-18T12:45:36.635411+00:00, execution_date=20250618T124536, start_date=20250618T124808, end_date=20250618T124809
[2025-06-18T12:48:09.083+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 691 for task evaluate_lasso (selected_features_path must be a .pkl file, got: /opt/***/data/models/selected_features.csv; 6170)
[2025-06-18T12:48:09.090+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-18T12:48:09.109+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-18T12:48:09.111+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
