[2025-06-19T08:45:35.400+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-19T08:45:35.427+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: usdpkr_forecasting.train_lasso manual__2025-06-19T08:45:16.886897+00:00 [queued]>
[2025-06-19T08:45:35.436+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: usdpkr_forecasting.train_lasso manual__2025-06-19T08:45:16.886897+00:00 [queued]>
[2025-06-19T08:45:35.437+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2025-06-19T08:45:35.449+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): train_lasso> on 2025-06-19 08:45:16.886897+00:00
[2025-06-19T08:45:35.454+0000] {standard_task_runner.py:63} INFO - Started process 749 to run task
[2025-06-19T08:45:35.457+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'usdpkr_forecasting', 'train_lasso', 'manual__2025-06-19T08:45:16.886897+00:00', '--job-id', '1073', '--raw', '--subdir', 'DAGS_FOLDER/usdpkr_forecasting_dag.py', '--cfg-path', '/tmp/tmp_9zpgq3l']
[2025-06-19T08:45:35.460+0000] {standard_task_runner.py:91} INFO - Job 1073: Subtask train_lasso
[2025-06-19T08:45:35.501+0000] {task_command.py:426} INFO - Running <TaskInstance: usdpkr_forecasting.train_lasso manual__2025-06-19T08:45:16.886897+00:00 [running]> on host 57c57e92cb28
[2025-06-19T08:45:35.613+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='usdpkr_forecasting' AIRFLOW_CTX_TASK_ID='train_lasso' AIRFLOW_CTX_EXECUTION_DATE='2025-06-19T08:45:16.886897+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-19T08:45:16.886897+00:00'
[2025-06-19T08:45:35.615+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-19T08:45:35.865+0000] {logging_mixin.py:188} INFO - Lasso: R2=0.5757, MSE=787.8511, MAE=23.2853
[2025-06-19T08:45:35.876+0000] {logging_mixin.py:188} INFO - Error predicting on full dataset (Lasso): [Errno 2] No such file or directory: '/opt/***/data/transformed_data.csv'
[2025-06-19T08:45:35.876+0000] {python.py:237} INFO - Done. Returned value was: ('/opt/***/data/models/usdpkr_lasso_model.pkl', '/opt/***/data/models/usdpkr_lasso_metrics.csv')
[2025-06-19T08:45:35.877+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-19T08:45:35.896+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=usdpkr_forecasting, task_id=train_lasso, run_id=manual__2025-06-19T08:45:16.886897+00:00, execution_date=20250619T084516, start_date=20250619T084535, end_date=20250619T084535
[2025-06-19T08:45:35.951+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-06-19T08:45:35.965+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-19T08:45:35.967+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
